### ISSUE TITLE
Bug: Redirect to room when already matched (Frontend)

### ISSUE THREAD

**Issue by gycgabriel** [CS3219-AY2324S1/ay2324s1-course-assessment-g11#213]

**Comment by ong6** [comment]
whats this bug about - could we get a description

**Comment by gycgabriel** [comment]
@ong6 after matched, it is possible to look for match ~~but it will not find any match because the user has been matched already~~

**Comment by gycgabriel** [comment]
You can try to reproduce by getting a match and clicking interviews and look for match
