### ISSUE TITLE
Frontend: Make the default match preference the same in settings and interview page

### ISSUE THREAD

**Issue by chunweii** [CS3219-AY2324S1/ay2324s1-course-assessment-g11#236]
If user has no match preferences, then the default shown in settings is c++ and medium, but in the interview page, it is python and medium. Let's change both to use python and medium.

**Comment by ong6** [comment]
i did this alr tho

**Comment by chunweii** [comment]
Ok, I realized my user has null default preferences. But the settings and the interview page showed different preferences. Perhaps, we can change it so that if there are no user preferences, we set it to python and medium (in settings and interview page)
