### ISSUE TITLE
Collaboration Service - Handle concurrent edits and conflicts in the collaboration space.

### ISSUE THREAD

**Issue by ong6** [CS3219-AY2324S1/ay2324s1-course-assessment-g11#40]

**Comment by gycgabriel** [comment]
To explore OT https://exaspark.medium.com/top-5-ways-to-implement-real-time-rich-text-editor-ranked-by-complexity-3bc26e3c777f

https://github.com/kbadk/json0-ot-diff

some possible libraries: CodeMirror

**Comment by gycgabriel** [comment]
Closed with https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g11/pull/57
