### ISSUE TITLE
Collaboration Service - Implement a save feature to review past sessions. 

### ISSUE THREAD

**Issue by ong6** [CS3219-AY2324S1/ay2324s1-course-assessment-g11#76]
Save past sessions in DB after the session is completed

**Comment by gycgabriel** [comment]
Do we need snapshots at certain points in time or is the final code enough?

If we need snapshots like google docs, when should we determine to save it?

**Comment by ong6** [comment]
No need for snapshots - just the final code version before a user leaves. 
-> we should also save these as sessions with the list of users which joined the session

But we have to autosave periodically or have a final session save in case all the users leave abruptly.
