### ISSUE TITLE
Question Service - to maintain a question repository indexed by difficulty level

### ISSUE THREAD

**Issue by ong6** [CS3219-AY2324S1/ay2324s1-course-assessment-g11#8]
- Setup MongoDB for questions 
- CRUD endpoints API spec 
- ...

**Comment by chunweii** [comment]
See [Project Planning]( https://docs.google.com/document/d/1HtozD6uyv9YNYNh5wBqVV7NcRSwggLglOfeRrWT3J4s/edit#heading=h.b5yytimeje4m) for a plan on the Question schemas on MongoDB and the API specification draft

**Comment by ong6** [comment]
LGTM at a high level

Perhaps we can consider adding the following stuff
1. Description - what this is at a high level
2. stats - how many people completed etc...
3. image - stored as array or URLs
4. source - e.g. leetcode
5. type - we can offer multiple choice, coding etc...
6. last updated - to know when it was previously updated

**Comment by chunweii** [comment]
> 3. image - stored as array or URLs

I think for images (or even videos?), we can just include the links in the markdown content
