### ISSUE TITLE
Question Service - Add new data types to support community authors

### ISSUE THREAD

**Issue by ong6** [CS3219-AY2324S1/ay2324s1-course-assessment-g11#81]

**Comment by chunweii** [comment]
Currently, there is a field in the mongodb schema called author (type string).

The Question type also includes an author attribute with type string.

As discussed, we can assign leetcode questions with the special author name "leetcode", or we can leave it blank. Also, we can store the user id as the author. 

The creation of question has not been linked to the frontend. I think that is the more critical issue to work on now
