### ISSUE TITLE
User Service - Record past sessions and questions attempted 

### ISSUE THREAD

**Issue by ong6** [CS3219-AY2324S1/ay2324s1-course-assessment-g11#95]
db design :

have 2 database: 

collab database 
- room id 
- uid 1 
- uid 2
- question id 
- question answer
- solve or not 
- etc... 

user qn database
- uid 
- question id
- question ans
- solved or not
- etc... 

mother ticket of #76

**Comment by gycgabriel** [comment]
Closed with #57
